on:
  push:
    branches:
      - github_actions_ci
      - develop
      - master

name: CI_CD

jobs:
  CI_CD:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-16.04, r: '3.6', rspm: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}
          - {os: windows-latest, r: '3.6'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: |
          remotes::install_cran(c("rstantools", "RBesT", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Install rmarkdown
        if: runner.os == 'Linux'
        run: Rscript -e 'install.packages("rmarkdown")'
        
      - name: Render README
        if: runner.os == 'Linux'
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
        
      - name: Commit and push README
        if: runner.os == 'Linux'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"

      - name: Install pkgdown
        if: runner.os == 'Linux'
        run: remotes::install_dev("pkgdown")
        shell: Rscript {0}

      - name: Install visR package
        if: runner.os == 'Linux'
        run: R CMD INSTALL .

      - name: Build visR package website
        if: runner.os == 'Linux'
        run: pkgdown::build_site()
        shell: Rscript {0}
        
      - name: Commit and push docs files
        if: runner.os == 'Linux'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          rm target_dir -rf
          git clone https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/openpharma/visR-docs.git target_dir
          copy docs target_dir
          git add target_dir
          git commit -m "Publish docs to this repo after build in main repo"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/openpharma/visR-docs.git master
