name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign issues and pull requests with `issue` label to project for everything else
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'issue') ||
        contains(github.event.pull_request.labels.*.name, 'issue')
      with:
        project: 'https://github.com/openpharma/visR/projects/2'
        column_name: 'Inbox'

    - name: Assign issues and pull requests with `idea` label to project for ideas
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'idea') ||
        contains(github.event.pull_request.labels.*.name, 'idea')
      with:
        project: 'https://github.com/openpharma/visR/projects/2'
        column_name: 'Proposed'
